version: '3.7'
services:
  db:
    image: mysql:5.7
    platform: linux/x86_64
    restart: always
    env_file: 
      - .env.local
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=dotz
    ports:
      - 3306:3306$DB_LOCAL_PORT
    volumes:
      - db:/var/lib/mysql

volumes:
  db: